### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dchiquito** [dchiquito/small-regent#5]
- [x] Start menu
- [ ] End credits
- [x] money counter
- [x] Planets with rings
- [x] animated non-walkable planets
- [x] face right when talking
- [x] Last level
- [x] Rebuild/rebalance big planets to tune down diffficulty
- [x] Dialog system
- [x] Writing the dialog
- [x] Tutorial tooltips
- [x] Level transitions
  - [x] Fadeout/fadein
- [x] Level manager
- [x] Final cut scene
- [x] Music
- [x] Sound effects
  - [x] Harpoon fire
  - [x] Harpoon flying
  - [x] Harpoon connection
  - [x] -Harpoon reeling-
  - [x] Landing
  - [x] Collecting money
  - [x] Interacting with orb
  - [x] Talking to rose
  - [x] Talking to merchant
- [ ] Particle effects
  - [ ] Harpoon impact
  - [x] Landing impact
  - [x] Collecting money
  - [x] collecting orbs
- [x] Animated paralax background
- [x] Game submission page
- [x] Credits for everything gleaned from the internet
